# Generated by Django 3.2.7 on 2022-03-29 03:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0002_alter_photos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
