# Generated by Django 3.2.7 on 2022-03-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0004_auto_20220330_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='first_name',
            new_name='name',
        ),
    ]
